package com.itech.utils.enums.units;

public enum HumidityUnits {
    HUMIDITYPERCENTAGE,
    HUMIDITYGRAMSPERCUBICMETER,
    HUMIDITYKILOGRAMSPERCUBICMETER,
    HUMIDITYGRAMSPERKILOGRAM,
    POUNDPERPOUND
}
