server.port=8080
thread.queue.size=10
database.ip.direction=localhost
database.port=3306
database.name=ITech
database.username=root
database.password=root
#multiple.anomaly.reporting=true
multiple.anomaly.reporting.amount=3
multiple.anomaly.reporting.time.interval=300
odoo.ip.direction=localhost
odoo.port=8069
odoo.database=odoo
odoo.user=odoo
odoo.password=odoo

unit.temperature=CENTIGRADE
unit.humidity=HUMIDITYPERCENTAGE
unit.vibration=VIBRATIONHERTZ
unit.pressure=ATMOSPHERES
unit.light=LUX
unit.sound=DECIBELS
unit.moisture=MOISTUREPERCENTAGE

limit.amount.temperature=100
limit.amount.humidity=98
limit.amount.vibration=3000
limit.amount.pressure=5
limit.amount.light=28000
limit.amount.sound=180
limit.amount.moisture=70