server.port=8080
thread.queue.size=10
database.ip.direction=localhost
database.port=3306
database.name=ITech
database.username=root
database.password=root

#limit.unit.temperature=CENTIGRADE
#limit.unit.humidity=PERCENTAGE
#limit.unit.vibration=HERTZ
#limit.unit.pressure=ATMOSPHERES
#limit.unit.light=LUX
#limit.unit.sound=DECIBELS
#limit.unit.moisture=PERCENTAGE
#
#limit.amount.temperature=100
#limit.amount.humidity=98
#limit.amount.vibration=3000
#limit.amount.pressure=5
#limit.amount.light=28000
#limit.amount.sound=180
#limit.amount.moisture=70