server.port=8080
thread.queue.size=10
unit.temperature=CENTIGRAD
unit.humidity=PERCENTAGE
unit.vibration=HERTZ
database.ip.direction=localhost
database.port=3306
database.name=ITech
database.username=root
database.password=root